### ISSUE TITLE
question about instance prompt/captions

### ISSUE THREAD

**Issue by adbrasi** [ThereforeGames/blora_for_kohya#3]
hello, friend. Thanks a lot for the info!
I have one question: 
In your tests, did you use captions? would it be possible to train as the authors provided in the examples "A [c] style" or "A [b]" <=(girl)?

**Comment by ThereforeGames** [comment]
Hi @adbrasi,

Yes, I do use `txt` file captions with B-LoRA and found it works great. The original B-LoRA trainer does not support captions, which was one of the motivations for bringing the method to sd-scripts.

But if your dataset doesn't contain caption files, sd-scripts will just refer to your folder name as an instance prompt. For example, you can call your folder `sks` and then use `in sks style` - it should produce the same results as the original B-LoRA method, if I'm not mistaken.
