### ISSUE TITLE
config file Error

### ISSUE THREAD

**Issue by audwns1gh** [ThereforeGames/blora_for_kohya#4]
Hello, I previously put the toml file generated at the start of training into --dataset_config, but I get an error. Is there a problem with the toml file?
-----my toml file------
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 2
dynamo_backend = "no"
enable_bucket = true
epoch = 1
gradient_accumulation_steps = 1
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 0.0003
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 225
max_train_epochs = 30
max_train_steps = 100
min_bucket_reso = 256
min_snr_gamma = 5
mixed_precision = "fp16"
network_alpha = 32
network_args = []
network_dim = 64
network_module = "networks.lora"
no_half_vae = true
noise_offset_type = "Original"
optimizer_args = []
optimizer_type = "AdamW"
output_dir = "C:/AI/output"
output_name = "BA_Aru01"
pretrained_model_name_or_path = "E:/Model/Pony/ponyDiffusionV6XL_v6StartWithThisOne.safetensors"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 5
save_model_as = "safetensors"
save_precision = "fp16"
text_encoder_lr = 0.00015
train_batch_size = 2
train_data_dir = "D:/dataset"
unet_lr = 0.0003
xformers = true
---------------------
When I tried the --dataset_config two paths the relative path and the absolute path, the error came out like this.
relative path
![1](https://github.com/user-attachments/assets/45b4756e-a91b-41d9-9e46-ca40384dc01e)
absolute path
![image](https://github.com/user-attachments/assets/479cf8e4-8d86-4a82-9463-b5712d0da25f)

Lastly, can I apply network_args in kohya gui? I think the difference between the training script is network_args, so I wonder if it is applied in gui.
I appreciate your time.

**Comment by ThereforeGames** [comment]
Hi @audwns1gh,

The error in your first image mentions the `bucket_no_upscale` flag:

```
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['bucket_no_upscale']
```

Here is an explanation for this error from the [Kohya error guide](https://github.com/kohya-ss/sd-scripts/blob/main/docs/config_README-en.md#error-guide):

> This error occurs when there is an option name that is not supported. It is highly likely that you misspelled the option name or mistakenly included it.

Someone opened [a similar issue here](https://github.com/bmaltais/kohya_ss/issues/2647), albeit for another flag.

The second error log is incomplete; there are probably more useful clues further up the console.

---

In response to your question:

> Lastly, can I apply network_args in kohya gui? I think the difference between the training script is network_args, so I wonder if it is applied in gui.

Sorry, I do not use the GUI. I would recommend asking about `network_args` support in [the GUI discussion board](https://github.com/bmaltais/kohya_ss/discussions).

**Comment by audwns1gh** [comment]
I modified the dataset config file and solved it, thank you.

**Comment by ThereforeGames** [comment]
Glad to hear that.
