### ISSUE TITLE
Can the slicer preserve CLIP?

### ISSUE THREAD

**Issue by slashedstar** [ThereforeGames/blora_for_kohya#5]
Atm the slicer discards all the clip weights (attention and MLP), could there be an option to keep CLIP?

**Comment by slashedstar** [comment]
Ok, I just added "lora_te" to the whitelist and it worked :)

**Comment by ThereforeGames** [comment]
Glad to hear it was easy!

For anyone else looking to make similar changes to the slicer: I recommend using `--debug` which will output a full list of block names to the console. From there, you can identify string patterns to include in your `blora_traits.json`.
